# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/s/ceres-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/s/ceres-common

PRODUCT_COPY_FILES += \
    vendor/s/ceres-common/proprietary/vendor/bin/hw/android.hardware.drm@1.2-service-lazy.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.2-service-lazy.widevine \
    vendor/s/ceres-common/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service-aw:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service-aw \
    vendor/s/ceres-common/proprietary/vendor/bin/hw/android.hardware.sensors@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors@2.0-service \
    vendor/s/ceres-common/proprietary/vendor/bin/hw/tee_supplicant:$(TARGET_COPY_OUT_VENDOR)/bin/hw/tee_supplicant \
    vendor/s/ceres-common/proprietary/vendor/bin/pvrsrvctl:$(TARGET_COPY_OUT_VENDOR)/bin/pvrsrvctl \
    vendor/s/ceres-common/proprietary/vendor/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_vendor.conf \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/boot_xr829.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/boot_xr829.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/bt_sdd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/bt_sdd.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/etf_xr829.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/etf_xr829.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/fw_xr829.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_xr829.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/fw_xr829_bt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_xr829_bt.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/firmware/sdd_xr829.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/sdd_xr829.bin \
    vendor/s/ceres-common/proprietary/vendor/etc/gsensor.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gsensor.cfg \
    vendor/s/ceres-common/proprietary/vendor/etc/hawkview/sensor_list_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/hawkview/sensor_list_cfg.ini \
    vendor/s/ceres-common/proprietary/vendor/etc/init/android.hardware.drm@1.2-service-lazy.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service-lazy.widevine.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-aw.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-aw.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/android.supplicant@2.5-optee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.supplicant@2.5-optee.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/init.display.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.display.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/init.gpu.property.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gpu.property.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/init.wireless.bluetooth.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wireless.bluetooth.rc \
    vendor/s/ceres-common/proprietary/vendor/etc/init/init.wireless.property.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wireless.property.rc \
    vendor/s/ceres-common/proprietary/vendor/firmware/rgx.fw.22.102.54.38:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw.22.102.54.38 \
    vendor/s/ceres-common/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/s/ceres-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/s/ceres-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/android.hardware.gatekeeper@1.0-impl-aw.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.gatekeeper@1.0-impl-aw.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/audio.primary.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/camera.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/gatekeeper.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/gatekeeper.soft.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.soft.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/gralloc.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/hwcomposer.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/lights.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/lights.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/memtrack.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/power.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/sound_trigger.primary.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sound_trigger.primary.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/hw/vulkan.ceres.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.ceres.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libAWIspApi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libAWIspApi.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libIMGegl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libIMGegl.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libMemAdapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMemAdapter.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxCore.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libOmxVdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxVdec.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libOmxVenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxVenc.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libVE.so:$(TARGET_COPY_OUT_VENDOR)/lib/libVE.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawavs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawavs.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawavs2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawavs2.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawh264.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawh264.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawh265.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawh265.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawh265soft.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawh265soft.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmjpeg.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmjpegplus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmjpegplus.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg2.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg4base.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg4base.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg4dx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg4dx.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg4h263.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg4h263.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg4normal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg4normal.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawmpeg4vp6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawmpeg4vp6.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawvp6soft.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawvp6soft.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawvp8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawvp8.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawvp9Hw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawvp9Hw.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawvp9HwAL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawvp9HwAL.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawvp9soft.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawvp9soft.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawwmv12soft.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawwmv12soft.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libawwmv3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawwmv3.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libcdc_base.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcdc_base.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libdisplayconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdisplayconfig.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libglslcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglslcompiler.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libisp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libisp.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libisp_ini.so:$(TARGET_COPY_OUT_VENDOR)/lib/libisp_ini.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libsrv_um.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsrv_um.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libteec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libteec.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libufwriter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libufwriter.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libusc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libusc.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libvdecoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdecoder.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libvenc_base.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvenc_base.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libvenc_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvenc_codec.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libvencoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvencoder.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libvideoengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvideoengine.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libwifi-hal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwifi-hal.so \
    vendor/s/ceres-common/proprietary/vendor/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so \
    vendor/s/ceres-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/s/ceres-common/proprietary/vendor/lib/optee_armtz/2233b43b-cec6-449a-9509469f5023e425.ta:$(TARGET_COPY_OUT_VENDOR)/lib/optee_armtz/2233b43b-cec6-449a-9509469f5023e425.ta \
    vendor/s/ceres-common/proprietary/vendor/lib/optee_armtz/663d017b-102d-4fe0-c086523e1c754846.ta:$(TARGET_COPY_OUT_VENDOR)/lib/optee_armtz/663d017b-102d-4fe0-c086523e1c754846.ta \
    vendor/s/ceres-common/proprietary/vendor/lib/vendor.display.config@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.display.config@1.0-impl.so \
    vendor/s/ceres-common/proprietary/vendor/lib/vendor.display.config@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.display.config@1.0.so

PRODUCT_PACKAGES += \
    keymaster-aw@4.0 \
    sensors@2.0 \
    vendor.display.config@1.0
